# Generated by Django 4.1.3 on 2022-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_caregory_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('tel_name', models.CharField(max_length=45)),
                ('email_name', models.CharField(max_length=45)),
                ('address_name', models.CharField(max_length=45)),
            ],
        ),
    ]
